name: gdbs

services:
  db:
    image: postgres:alpine3.20
    restart: always
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_PORT=$POSTGRES_PORT
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - ./minio_data:/data
    ports:
      - '9000:9000'
      - '9001:9001'
