services:
  db:
    image: postgres:alpine3.20
    restart: on-failure
    env_file:
      - ./postgres.secret.env
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"